= Advanced Service Mesh Lab Assets

== Purpose

. Add additional admin[1-100] users to the htpassword IDM provider used by OpenShift
. Install the elasticsearch operator
. Install the jaeger operator
. Install the kiali operator
. Install the istio / maistra operator
. Install istio control planes for each student of the course
. Add additional permissions to users needed for the labs executed by students
. Optional:  Seed 3scale API Mgmt tenants with _incident-service_ related API resources 

== Procedure

. Provision an OCP4 lab environment
. Optional: Install 3scale API Manager and tenants as per github.com/gpe-mw-ansible-org/3scale_multitenant
. Ensure you are authenticated into the OCP4 lab environment as a cluster-admin
. Clone this repository and execute:
+
-----
cd ansible

export api_mgmt_subdomain_base=<change me>                        # ie: cluster-168d.168d.example.opentlc.com
export create_incident_service_api_resources=false                # Please see comments in playbooks/group_vars/all/vars.yml
start_id=24
end_id=25

$ ansible-playbook -i localhost, -c local playbooks/advanced_service_mesh_lab_setup.yml \
    -e "create_incident_service_api_resources=$create_incident_service_api_resources" \
    -e "api_mgmt_subdomain_base=$api_mgmt_subdomain_base" \
    -e "start_id=$start_id" \
    -e "end_id=$end_id"
-----
